FROM node:8-slim
WORKDIR /app 

COPY ./frontend/*.json ./
RUN npm install 
COPY ./frontend ./

#Change localhost for my IP 
RUN sed -i 's/localhost:8000/151.248.114.167:8000/g' src/*Api.js && \
    sed -i 's/localhost:8000/151.248.114.167:8000/g' src/*API.js

CMD [ "npm", "start" ] 


